(()=>{
'use strict';
const Y=2026,F='https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl',CORE='https://sports.core.api.espn.com/v3/sports/football/nfl/athletes?active=true&limit=2000',DS='https://api.parse.bot/scraper/8cbb56cd-270c-41c6-ab5b-ff713cf1ef13';
const FP=new Set(['QB','RB','WR','TE','K']),OFF=new Set(['QB','RB','FB','WR','TE','OT','T','LT','RT','OG','G','LG','RG','C','OL']),DEF=new Set(['DT','NT','DE','DL','EDGE','LB','ILB','OLB','CB','S','FS','SS','DB']),ST=new Set(['K','P','PK','LS']);
const PM={1:'QB',2:'RB',3:'WR',4:'TE',5:'K',7:'P',9:'DT',10:'DE',11:'LB',12:'CB',13:'S'},TM={0:'FA',1:'ATL',2:'BUF',3:'CHI',4:'CIN',5:'CLE',6:'DAL',7:'DEN',8:'DET',9:'GB',10:'TEN',11:'IND',12:'KC',13:'LV',14:'LAR',15:'MIA',16:'MIN',17:'NE',18:'NO',19:'NYG',20:'NYJ',21:'PHI',22:'ARI',23:'PIT',24:'LAC',25:'SF',26:'SEA',27:'TB',28:'WSH',29:'CAR',30:'JAX',33:'BAL',34:'HOU'};
const TN={ARI:'Arizona Cardinals',ATL:'Atlanta Falcons',BAL:'Baltimore Ravens',BUF:'Buffalo Bills',CAR:'Carolina Panthers',CHI:'Chicago Bears',CIN:'Cincinnati Bengals',CLE:'Cleveland Browns',DAL:'Dallas Cowboys',DEN:'Denver Broncos',DET:'Detroit Lions',GB:'Green Bay Packers',HOU:'Houston Texans',IND:'Indianapolis Colts',JAX:'Jacksonville Jaguars',KC:'Kansas City Chiefs',LV:'Las Vegas Raiders',LAC:'Los Angeles Chargers',LAR:'Los Angeles Rams',MIA:'Miami Dolphins',MIN:'Minnesota Vikings',NE:'New England Patriots',NO:'New Orleans Saints',NYG:'New York Giants',NYJ:'New York Jets',PHI:'Philadelphia Eagles',PIT:'Pittsburgh Steelers',SEA:'Seattle Seahawks',SF:'San Francisco 49ers',TB:'Tampa Bay Buccaneers',TEN:'Tennessee Titans',WSH:'Washington Commanders'};
const S={players:[],teams:[],team:'',group:'all',sort:{k:'name',d:1},ds:new Map(),practice:new Map(),updated:null,source:'fantasy'};
const $=q=>document.querySelector(q),E={search:$('#search'),pos:$('#posFilter'),health:$('#healthFilter'),rows:$('#rows'),empty:$('#empty'),load:$('#loadState'),key:$('#dsKey'),score:$('#scoring'),league:$('#leagueType'),picker:$('#teamPicker'),menu:$('#teamMenu'),teamBtn:$('#teamButton'),teamLogo:$('#teamButtonLogo'),teamText:$('#teamButtonText')};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,''),num=v=>{let n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null},logo=a=>a?`https://a.espncdn.com/i/teamlogos/nfl/500/${a.toLowerCase()}.png`:'',head=id=>`https://a.espncdn.com/i/headshots/nfl/players/full/${id}.png`;
function toast(m){let t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),4200)}
function health(src,cls,text){$(`#${src}Dot`).className=`dot ${cls}`;$(`#${src}Health`).textContent=text}
function pgroup(p){return FP.has(p)?'fantasy':OFF.has(p)?'offense':DEF.has(p)?'defense':ST.has(p)?'st':'other'}
function hclass(s){s=String(s||'').toLowerCase();return/out|reserve|ir|suspend/.test(s)?'red':/doubt/.test(s)?'orange':/question|limited|day.to.day/.test(s)?'yellow':'green'}
function rclass(r){return r==null?'blue':r>=60?'red':r>=35?'orange':r>=20?'yellow':'green'}
async function json(url,opt={}){let c=new AbortController(),tm=setTimeout(()=>c.abort(),25000);try{let r=await fetch(url,{...opt,signal:c.signal,cache:'no-store'}),t=await r.text();if(!r.ok)throw Error(`${r.status} ${r.statusText}: ${t.slice(0,180)}`);return JSON.parse(t)}finally{clearTimeout(tm)}}
async function active(){let u=`${F}/seasons/${Y}/players?scoringPeriodId=0&view=players_wl`,d=await json(u,{headers:{'x-fantasy-filter':JSON.stringify({filterActive:{value:true}}),accept:'application/json'}});return Array.isArray(d)?d:d.players||[]}
async function kona(filter,view='kona_player_info'){return json(`${F}/seasons/${Y}/segments/0/leaguedefaults/3?scoringPeriodId=0&view=${view}`,{headers:{'x-fantasy-filter':JSON.stringify(filter),accept:'application/json'}})}
async function core(){let d=await json(CORE,{headers:{accept:'application/json'}});return d.items||d.athletes||[]}
function po(e){return e?.player||e?.playerPoolEntry?.player||e||{}}
function statsArr(e,p){return[...(p?.stats||[]),...(e?.playerPoolEntry?.stats||[]),...(e?.stats||[])]}
function stat(e,p,src){return statsArr(e,p).find(x=>+x.seasonId===Y&&+x.statSourceId===src&&+x.statSplitTypeId===0)||statsArr(e,p).find(x=>+x.seasonId===Y&&+x.statSourceId===src)||null}
function mkst(s){let x=s?.stats||{},o={passYds:+(x[3]??x[22]??0),passTD:+(x[4]||0),ints:+(x[20]||0),rushAtt:+(x[23]||0),rushYds:+(x[24]??x[40]??0),rushTD:+(x[25]||0),rec:+(x[41]??x[53]??0),recYds:+(x[42]||0),recTD:+(x[43]||0),lostFum:+(x[72]||0)};o.fantasy=o.passYds/25+o.passTD*4-o.ints*2+o.rushYds/10+o.rushTD*6+o.recYds/10+o.recTD*6+o.rec*.5-o.lostFum*2;return o}
function injury(raw,flag){let s=String(raw||'').trim();if(!s&&!flag)return null;let k=s.toUpperCase().replace(/[_-]/g,' '),m={ACTIVE:'',QUESTIONABLE:'Questionable',DOUBTFUL:'Doubtful',OUT:'Out','INJURY RESERVE':'Injured Reserve','INJURED RESERVE':'Injured Reserve',IR:'Injured Reserve',SUSPENDED:'Suspended'};s=m[k]!==undefined?m[k]:(s||'Injured').replace(/\b\w/g,c=>c.toUpperCase());return s?{status:s}:null}
function fantasy(e,base={}){let p={...po(base),...po(e)},pos=PM[+p.defaultPositionId];if(!pos)return null;let a=stat(e,p,0),pr=stat(e,p,1),tid=+(p.proTeamId??a?.proTeamId??pr?.proTeamId??0),ta=TM[tid]||'FA',id=String(p.id||e?.id||'');if(!id||ta==='FA')return null;return{id,name:p.fullName||p.displayName||'Unknown',position:pos,group:pgroup(pos),teamAbbr:ta,teamName:TN[ta]||ta,teamLogo:logo(ta),headshot:p.headshot?.href||head(id),jersey:p.jersey||'',experience:p.experience?.years??p.experience??'',active:p.active!==false,injury:injury(p.injuryStatus,p.injured),actual:mkst(a),projected:mkst(pr),raw:p,source:'fantasy'}}
function npos(p){let s=String(p||'').toUpperCase().replace(/[^A-Z]/g,''),m={OFFENSIVETACKLE:'OT',OFFENSIVEGUARD:'OG',CENTER:'C',DEFENSIVETACKLE:'DT',DEFENSIVEEND:'DE',LINEBACKER:'LB',CORNERBACK:'CB',SAFETY:'S',LONGSNAPPER:'LS',PUNTER:'P',KICKER:'K',FULLBACK:'FB'};return m[s]||s}
function corep(a){a=a?.athlete||a||{};let id=String(a.id||''),pos=npos(a.position?.abbreviation||a.position?.displayName||a.position),tid=+(a.team?.id||a.teamId||0),ta=String(a.team?.abbreviation||TM[tid]||'').toUpperCase();if(!id||!pos||!ta||ta==='FA')return null;return{id,name:a.fullName||a.displayName||[a.firstName,a.lastName].filter(Boolean).join(' '),position:pos,group:pgroup(pos),teamAbbr:ta,teamName:a.team?.displayName||TN[ta]||ta,teamLogo:a.team?.logos?.[0]?.href||logo(ta),headshot:a.headshot?.href||a.headshot||head(id),jersey:a.jersey||'',experience:a.experience?.years??a.experience??'',active:a.active!==false,injury:injury(a.injuryStatus,a.injured),actual:mkst(null),projected:mkst(null),raw:a,source:'core'}}
function merge(a,b){return{...a,...b,position:b?.position||a?.position,group:pgroup(b?.position||a?.position),teamLogo:b?.teamLogo||a?.teamLogo,headshot:b?.headshot||a?.headshot,injury:b?.injury||a?.injury,source:a&&b?'core+fantasy':(b?'fantasy':'core')}}
function ds(p){return S.ds.get(norm(p.name))}function pr(p){return S.practice.get(norm(p.name))||{}}function rowp(p){let d=ds(p);return{...p,ds:d,practice:pr(p),risk:num(d?.injury_risk),rank:num(d?.rank)}}
function practiceBadge(x){if(!x)return'<span class="practice none">—</span>';let c=x.code==='FULL'?'full':x.code==='LIMITED'?'limited':x.code==='DNP'?'dnp':'other';return`<span class="practice ${c}" title="${esc(x.text||x.code)}">${esc(x.code)}</span>`}
function rebuild(){let ab=[...new Set(S.players.map(p=>p.teamAbbr))].filter(Boolean).sort();S.teams=ab.map(a=>({a,n:TN[a]||a,l:logo(a)}));teamMenu();let ps=[...new Set(S.players.map(p=>p.position))].filter(Boolean).sort(),cur=E.pos.value;E.pos.innerHTML='<option value="">All positions</option>'+ps.map(p=>`<option>${esc(p)}</option>`).join('');if(ps.includes(cur))E.pos.value=cur}
function teamMenu(){let c=S.teams.find(x=>x.a===S.team);E.teamLogo.innerHTML=c?`<img src="${c.l}" alt="">`:'';E.teamText.textContent=c?c.n:'All teams';E.menu.innerHTML=`<button class="team-option ${!S.team?'on':''}" data-team=""><span style="width:24px;text-align:center">🏈</span><span>All teams</span></button>`+S.teams.map(t=>`<button class="team-option ${S.team===t.a?'on':''}" data-team="${t.a}"><img src="${t.l}" alt=""><span>${esc(t.n)}</span><small>${t.a}</small></button>`).join('');E.menu.querySelectorAll('button').forEach(b=>b.onclick=()=>{S.team=b.dataset.team||'';E.picker.classList.remove('open');teamMenu();render()})}
async function loadESPN(){health('espn','busy','loading');E.load.innerHTML='<span class="spinner"></span> Loading ESPN…';try{let ar=await active();if(!ar.length)throw Error('players_wl returned 0 players');let m=new Map(ar.map(x=>fantasy(x,x)).filter(Boolean).map(p=>[p.id,p]));S.players=[...m.values()];S.updated=new Date();rebuild();render();let kf={players:{limit:2000,sortPercOwned:{sortPriority:4,sortAsc:false},filterStatsForTopScoringPeriodIds:{value:18,additionalValue:[`00${Y}`,`10${Y}`]}}};let [kr,cr]=await Promise.allSettled([kona(kf),core()]);if(cr.status==='fulfilled'){for(let x of cr.value){let c=corep(x);if(!c)continue;m.set(c.id,m.has(c.id)?merge(c,m.get(c.id)):c)}S.source='core+fantasy'}if(kr.status==='fulfilled'){for(let e of kr.value.players||[]){let id=String(po(e).id||e.id||''),f=fantasy(e,m.get(id)?.raw);if(f)m.set(id,m.has(id)?merge(m.get(id),f):f)}}S.players=[...m.values()].filter(p=>p.active&&p.teamAbbr);rebuild();health('espn','ok',`${S.players.length} active · ${S.source}`);toast(`ESPN loaded ${S.players.length} active players.`)}catch(e){console.error(e);health('espn','bad','failed');toast('ESPN load failed: '+e.message)}finally{E.load.textContent='';render()}}
async function dsget(ep,p={}){if(!E.key.value.trim())throw Error('Enter a Parse API key first.');let q=new URLSearchParams();Object.entries(p).forEach(([k,v])=>q.set(k,v??''));return json(`${DS}/${ep}?${q}`,{headers:{'X-API-Key':E.key.value.trim()}})}
function articles(x){return Array.isArray(x)?x:(x?.data?.articles||x?.articles||x?.data?.news||x?.news||[])}
function pstat(t){t=String(t||'').toLowerCase();if(!/practic/.test(t))return null;if(/did not (participate|practice)|didn't practice|non[- ]participant|\bdnp\b|held out|missed practice/.test(t))return{code:'DNP',text:'Did not practice'};if(/limited( participant| participation)?|limited in practice/.test(t))return{code:'LIMITED',text:'Limited practice'};if(/full participant|full participation|practiced in full|full practice/.test(t))return{code:'FULL',text:'Full practice'};if(/returned to practice|participated in practice/.test(t))return{code:'PRACTICE',text:'Practiced'};return null}
function pday(a,t){t=t.toLowerCase();if(t.includes('wednesday'))return'wed';if(t.includes('thursday'))return'thu';if(t.includes('friday'))return'fri';let d=new Date(a.date||a.published_at||a.timestamp||'');return Number.isNaN(+d)?null:({3:'wed',4:'thu',5:'fri'})[d.getDay()]||null}
function indexNews(as){S.practice=new Map();let names=S.players.map(p=>[norm(p.name),p.name]);for(let a of as){let text=[a.title,a.summary,a.description,a.content].filter(Boolean).join(' '),st=pstat(text),day=pday(a,text);if(!st||!day)continue;let name=a?.player?.name||a.player_name||a.playerName||a?.players?.[0]?.name||'',key=norm(name);if(!key){let nt=norm(text),hit=names.find(([k])=>k.length>4&&nt.includes(k));if(hit)key=hit[0]}if(!key)continue;let r=S.practice.get(key)||{},when=+new Date(a.date||a.published_at||0)||0;if(!r[day]||when>=r[day].when)r[day]={...st,when};S.practice.set(key,r)}}
async function loadDS(){if(!E.key.value.trim())return toast('Enter your Parse API key first.');health('ds','busy','loading');$('#loadDSBtn').disabled=true;try{let [rr,nr]=await Promise.allSettled([dsget('get_rankings',{depth:'rankings',scoring:E.score.value,position:'',is_dynasty:'false',league_type:E.league.value}),dsget('get_news_articles')]);if(rr.status!=='fulfilled')throw rr.reason;let ps=rr.value?.data?.players||rr.value?.players||[];S.ds=new Map(ps.map(p=>[norm(p.name),p]));if(nr.status==='fulfilled')indexNews(articles(nr.value));health('ds','ok',`${ps.length} ranked · ${S.practice.size} practice`);toast(`DraftSharks: ${ps.length} rankings, ${S.practice.size} practice players.`);render()}catch(e){health('ds','bad','failed');toast('DraftSharks load failed: '+e.message)}finally{$('#loadDSBtn').disabled=false}}
function matchGroup(p){return S.group==='all'||(S.group==='fantasy'?FP.has(p.position):p.group===S.group)}
function filtered(){let q=norm(E.search.value),hf=E.health.value,ps=E.pos.value,a=S.players.map(rowp).filter(p=>{if(q&&!norm(`${p.name} ${p.teamName} ${p.teamAbbr} ${p.position}`).includes(q))return false;if(S.team&&p.teamAbbr!==S.team)return false;if(ps&&p.position!==ps)return false;if(!matchGroup(p))return false;let x=p.practice||{};if(hf==='injured'&&!p.injury)return false;if(hf==='healthy'&&p.injury)return false;if(hf==='practice'&&!['wed','thu','fri'].some(d=>x[d]))return false;if(hf==='dnp'&&!['wed','thu','fri'].some(d=>x[d]?.code==='DNP'))return false;if(hf==='limited'&&!['wed','thu','fri'].some(d=>x[d]?.code==='LIMITED'))return false;if(hf==='highrisk'&&!(p.risk>=50))return false;return true});let{k,d}=S.sort;return a.sort((x,y)=>{let A=x[k],B=y[k];if(['risk','rank'].includes(k)){A=A??99999;B=B??99999;return(A-B)*d}return String(A??'').localeCompare(String(B??''),undefined,{numeric:true})*d})}
function render(){let a=filtered();$('#countPlayers').textContent=a.length;$('#countTeams').textContent=S.teams.length;$('#countInjured').textContent=S.players.filter(p=>p.injury).length;$('#countPractice').textContent=S.players.filter(p=>{let x=pr(p);return['wed','thu','fri'].some(d=>['DNP','LIMITED'].includes(x[d]?.code))}).length;$('#countDS').textContent=S.players.filter(p=>ds(p)).length;$('#lastUpdated').textContent=S.updated?S.updated.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—';document.querySelectorAll('.chip').forEach(b=>b.classList.toggle('on',b.dataset.group===S.group));if(!a.length){E.rows.innerHTML='';E.empty.style.display='block';E.empty.textContent=S.players.length?'No players match the filters.':'No ESPN data loaded.';return}E.empty.style.display='none';E.rows.innerHTML=a.map(p=>{let x=p.practice||{},d=p.ds,ht=p.injury?.status||'Active / no injury';return`<tr class="clickable" data-id="${p.id}"><td><div class="player"><img class="headshot" src="${p.headshot}" onerror="this.style.opacity=.15"><div><div class="pname">${esc(p.name)}</div><div class="meta">${FP.has(p.position)?`${Y}: ${p.actual.fantasy.toFixed(1)} half-PPR`:`${p.group} · ESPN`}</div></div></div></td><td><div class="teamcell"><img class="logo" src="${p.teamLogo}"><span>${p.teamAbbr}</span></div></td><td><span class="badge blue">${p.position}</span></td><td><span class="badge ${p.injury?hclass(ht):'green'}">${esc(ht)}</span></td><td>${practiceBadge(x.wed)}</td><td>${practiceBadge(x.thu)}</td><td>${practiceBadge(x.fri)}</td><td>${p.risk==null?'—':`<b>${p.risk}%</b><div class="riskbar"><div class="riskfill" style="width:${Math.min(100,p.risk)}%"></div></div>`}</td><td>${d?.rank?`#${d.rank}`:'—'}</td><td>${d?.ds_projection??d?.consensus??(FP.has(p.position)?p.projected.fantasy.toFixed(1):'—')}</td><td>${d?.adp??'—'}</td><td>${d?.bye??'—'}</td><td>${esc(p.jersey||'—')}</td><td>${esc(p.experience||'—')}</td></tr>`}).join('');E.rows.querySelectorAll('tr').forEach(r=>r.onclick=()=>openPlayer(r.dataset.id))}
function detailPractice(x){return`<div class="practice-grid">${[['WED','wed'],['THU','thu'],['FRI','fri']].map(([l,k])=>`<div class="practice-day"><small>${l}</small>${practiceBadge(x[k])}</div>`).join('')}</div><div class="source-note">Practice values are inferred from recent DraftSharks news summaries when available.</div>`}
async function openPlayer(id){let p=S.players.map(rowp).find(x=>x.id===id);if(!p)return;$('#drawerBackdrop').classList.add('open');let prof=null;if(FP.has(p.position)){let filter={players:{filterIds:{value:[+id]},limit:1,sortPercOwned:{sortPriority:1,sortAsc:false},filterStatsForTopScoringPeriodIds:{value:18,additionalValue:[`00${Y}`,`10${Y}`]}}},jobs=[kona(filter,'kona_playercard')];if(p.ds?.id&&E.key.value.trim())jobs.push(dsget('get_player_profile',{player_id:p.ds.id}));let rs=await Promise.allSettled(jobs);let e=rs[0].status==='fulfilled'?(rs[0].value.players||[])[0]:null;if(e){let f=fantasy(e,p.raw),i=S.players.findIndex(x=>x.id===id);if(f&&i>=0){S.players[i]=merge(S.players[i],f);p=rowp(S.players[i]);render()}}if(rs[1]?.status==='fulfilled')prof=rs[1].value}let fantasyBlock=FP.has(p.position)?`<div class="card"><h3>Fantasy snapshot</h3><div class="kv"><div>DS rank</div><div>${p.ds?.rank?'#'+p.ds.rank:'—'}</div><div>ADP</div><div>${p.ds?.adp||'—'}</div><div>DS projection</div><div>${p.ds?.ds_projection||p.ds?.consensus||'—'}</div><div>ESPN projected half-PPR</div><div>${p.projected.fantasy.toFixed(1)}</div></div></div>`:`<div class="card"><h3>Non-fantasy position</h3><div class="hint">Included from ESPN's broader active-athlete feed. DraftSharks fantasy ranking fields are intentionally blank.</div></div>`;$('#drawerBody').innerHTML=`<div class="hero"><img class="headshot" src="${p.headshot}"><div><h2>${esc(p.name)}</h2><div class="teamcell"><img class="logo" src="${p.teamLogo}"><b>${esc(p.teamName)}</b> · ${p.position}</div><div class="meta">ESPN ID ${p.id} · ${p.source}</div></div></div><div class="cards"><div class="card"><h3>Health</h3><div class="kv"><div>ESPN status</div><div><span class="badge ${p.injury?hclass(p.injury.status):'green'}">${esc(p.injury?.status||'Active / no injury')}</span></div><div>DS injury risk</div><div><span class="badge ${rclass(p.risk)}">${p.risk==null?'—':p.risk+'%'}</span></div><div>Position group</div><div>${p.group}</div></div></div><div class="card"><h3>WED / THU / FRI</h3>${detailPractice(p.practice||{})}</div></div>${fantasyBlock}${prof?`<div class="card"><h3>DraftSharks profile response</h3><div class="raw">${esc(JSON.stringify(prof,null,2).slice(0,12000))}</div></div>`:''}`}
function reset(){E.search.value='';E.pos.value='';E.health.value='';S.team='';S.group='all';teamMenu();render()}
E.search.oninput=render;E.pos.onchange=render;E.health.onchange=render;$('#quickbar').onclick=e=>{let b=e.target.closest('[data-group]');if(b){S.group=b.dataset.group;render()}};E.teamBtn.onclick=()=>E.picker.classList.toggle('open');document.addEventListener('click',e=>{if(!E.picker.contains(e.target))E.picker.classList.remove('open')});document.querySelectorAll('th.sort').forEach(th=>th.onclick=()=>{let k=th.dataset.sort;if(S.sort.k===k)S.sort.d*=-1;else S.sort={k,d:1};render()});$('#refreshBtn').onclick=loadESPN;$('#resetBtn').onclick=reset;$('#loadDSBtn').onclick=loadDS;$('#testBtn').onclick=async()=>{try{health('espn','busy','testing');let a=await active();health('espn','ok',a.length+' active')}catch(e){health('espn','bad','error')}if(E.key.value.trim())try{health('ds','busy','testing');await dsget('get_news_articles');health('ds','ok','online')}catch(e){health('ds','bad','error')}};$('#closeDrawer').onclick=()=>$('#drawerBackdrop').classList.remove('open');$('#drawerBackdrop').onclick=e=>{if(e.target.id==='drawerBackdrop')e.currentTarget.classList.remove('open')};E.key.value=sessionStorage.getItem('ds_api_key')||'';E.key.onchange=()=>E.key.value.trim()?sessionStorage.setItem('ds_api_key',E.key.value.trim()):sessionStorage.removeItem('ds_api_key');teamMenu();loadESPN();
})();
